### ISSUE TITLE
Empty NUC_FASTA_OUT

### ISSUE THREAD

**Issue by GomathiNayagam** [ncbi/amr#115] opened 2023-03-21 05:31 UTC
Hi,
I am trying to find AMR genes in NUC_FASTA. Though AMRfinder identifies AMR in the input, it outputs an empty NUC_FASTA_OUT. I am probably making a silly error here. Could you help me out?

`amrfinder --nucleotide $NUC_FASTA  --ident_min 0.9 --coverage_min 0.89 --nucleotide_output out.fasta --threads 6 --output amrout.tsv`

**Comment by evolarjun** [comment] 2023-03-21 12:15
Hi @GomathiNayagam ,

I don't see a silly error, and I'm having trouble reproducing your issue. With the test data distributed with AMRFinderPlus I get FASTA output:

```
$ NUC_FASTA=test_dna.fa
$ amrfinder --nucleotide $NUC_FASTA  --ident_min 0.9 --coverage_min 0.89 --nucleotide_output out.fasta --threads 6 --output amrout.tsv
Running: amrfinder --nucleotide test_dna.fa --ident_min 0.9 --coverage_min 0.89 --nucleotide_output out.fasta --threads 6 --output amrout.tsv
Software directory: '/panfs/pan1.be-md.ncbi.nlm.nih.gov/bacterial_pathogens/backup/packages/AMRFinderPlus_v3.11.4/'
Software version: 3.11.4
Database directory: '/panfs/pan1.be-md.ncbi.nlm.nih.gov/bacterial_pathogens/backup/packages/AMRFinderPlusData/2023-02-23.1'
Database version: 2023-02-23.1
AMRFinder translated nucleotide search
  - include -O ORGANISM, --organism ORGANISM option to add mutation searches and suppress common proteins
Running blastx ...
Making report ...
AMRFinder took 9 seconds to complete
```
The results look as I would expect:
```
$ wc -l amrout.tsv
6 amrout.tsv
$ fgrep -c '>' out.fasta
5
```

Could you paste in what AMRFinderPlus prints to the screen and attach you $NUC_FASTA file?  That might help me reproduce your issue.

Thanks,
Arjun

**Comment by GomathiNayagam** [comment] 2023-03-21 12:56
Hi,
I too tried with the test data and it produces nuc_output. But it doesn't work for my file. So, I think it could be an error from my file. Please find my fasta file attached.

This is what the AMRfinder prints out.
```
Software directory: '/home/gomathinayagam/miniconda3/envs/amrfinder/bin/'
Software version: 3.11.4
Database directory: '/home/gomathinayagam/miniconda3/envs/amrfinder/share/amrfinderplus/data/2023-02-23.1'
Database version: 2023-02-23.1
AMRFinder translated nucleotide search
  - include -O ORGANISM, --organism ORGANISM option to add mutation searches and suppress common proteins
Running tblastn ...
Making report ...
AMRFinder took 16 seconds to complete
```
[test.gz](https://github.com/ncbi/amr/files/11028474/test.gz)

**Comment by vbrover** [comment] 2023-03-21 14:41
Thank you for reporting this!
It is a bug in `amrfinder`: leading underscore symbol is trimmed from the contig name in the report.
This will be fixed in version 3.11.5.

**Comment by GomathiNayagam** [comment] 2023-03-22 04:32
Yes, it is the 'unusual' FASTA header. It works after editing the headers.
Thank you very much!

**Comment by evolarjun** [comment] 2023-03-22 15:43
@GomathiNayagam  I'm glad to hear it's working for you.

I'm going to reopen just for our tracking because we consider this a bug and plan to release a fix with the next AMRFinderPlus software release.

Thanks for reporting!

**Closed** 2023-05-10 14:51 UTC
Labels: bug
